#!/bin/bash
# transpose1
#PBS -N Tjob
#PBS -o ./Tjob.o
#PBS -e ./Tjob.e
#queue name
#PBS -q short_cpuQ
#set time
#PBS -l walltime=0:10:00
#PBS -l select=1:ncpus=64:ompthreads=64:mem=4gb

module load gcc91
gcc() {
   gcc-9.1.0 "$@"
}
gcc --version
cd /home/leonardo.chiste/transpose

gcc -o transp transp.c -fopenmp -O2
./transp 16
./transp 32
./transp 64
./transp 128
./transp 256
./transp 512
./transp 1024
./transp 2048
./transp 4096
